### ISSUE TITLE
Particle Argon - Compile Error reference to 'Record' is ambiguous

### ISSUE THREAD

**Issue by tgourley** [mrhornsby/spark-core-mdns#25]
I am trying to put the example app on my Particle Argon.  I am getting the following error when trying to compile. 

`In file included from c:/Users/Trey/Documents/Development/personal/particleprojects/PingBack/lib/MDNS/src/Label.h:7:0,
                 from c:/Users/Trey/Documents/Development/personal/particleprojects/PingBack/lib/MDNS/src/MDNS.h:7,
                 from c:/Users/Trey/Documents/Development/personal/particleprojects/PingBack/src/PingBack.ino:1:
c:/Users/Trey/Documents/Development/personal/particleprojects/PingBack/lib/MDNS/src/Record.h:70:24: error: reference to 'Record' is ambiguous
 class ARecord : public Record {
                        ^
c:/Users/Trey/Documents/Development/personal/particleprojects/PingBack/lib/MDNS/src/Record.h:28:7: note: candidates are: class Record
 class Record {`

**Comment by tgourley** [comment]
A little research, it appears that there is a Record class related to NFC.

https://github.com/particle-iot/device-os/blob/develop/wiring/inc/spark_wiring_nfc.h

**Comment by mrhornsby** [comment]
Thanks @tgourley, I probably should have namespaces this when I started. I'll create a new major version (I'm guessing the namespace will break peoples code).

**Comment by mrhornsby** [comment]
v2.0.0 released. Should be available any moment now.

**Comment by tgourley** [comment]
Adding the namespace worked like a charm.  Thank you!
